#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#

if ! grep  --only-matching amulet <<< $I &> /dev/null; then
    cat << EOF
你找到了一个绿宝石护身符！"

为了收集宝藏，你必须有一个变量来存放你的库存。

创建一个变量，像这样把你的财宝加入其中。

export I=amulet,$I

你可以随时用这个命令检查你的财富。

echo \$I


EOF
    mv ../.chapel ../chapel 2>/dev/null
    mv ../.vault ../vault 2>/dev/null
    mv ../.scrap ../scrap 2>/dev/null
else
    echo "这个宝藏被取走了。"
fi


















































































































































































































































































# Hmm, that didn't work.
# Try moving into the armoury, maybe you
# can come back to this treasure later!


