#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
cat << EOF 
你发现了一个旋转着的绿色液体的药水瓶。你想喝它吗？  y/n

EOF
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
   cat << EOF 
一种质朴的绿色植物的味道充满了你的嘴。 它温暖并增强了你的力量。

为你的健康点数（HP）创建一个变量。 你有 15 HP。

export HP=15

EOF
else
    cat << EOF
你又不傻，怎么会相信这样的东西呢：这药水可能是毒药。 

为你的健康点数（HP）创建一个变量。 你有 10 HP。

export HP=10

EOF

fi

cat << EOF
你可以在任何时候检查你的健康状况。

echo \$HP

EOF
mv ../../.chapel ../../chapel 2>/dev/null
mv ../../.vault ../../vault 2>/dev/null
mv ../../.scrap ../../scrap 2>/dev/null




















































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./potion

