#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#


gameover () {
    cat << EOF > corpse
你看到一个被杀的冒险者的尸体在地牢的地板上。你在尸体上发现了以下物品。 

${I}

EOF
    curr=`basename $PWD`
    while [ "$curr" != "entrance" ]; do
        pushd .. &> /dev/null
        dirs -c
        curr=`basename $PWD`
    done
    unset I
    unset HP
    $SHELL
}

penguin_bite () {
    cat << EOF
企鹅咬着你的储物袋，希望能吃到一点东西。 没有发现什么，它咬了一口你的手，造成1点伤害。(让 "HP=HP-1")。 如果你有一把剑并希望攻击企鹅，你可以避免这个伤害。

EOF
printf "你要攻击企鹅吗？ y/n  "
	read RESP
	if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
        cat << EOF
你攻击企鹅，快速地用一刀把它做掉。 这引起了房间里其他企鹅的注意。 它们联合起来，冲向你。你拼尽全力。

EOF
        let HP=HP-5
        export HP
        if [ "$HP" -le 0 ]; then
            cat << EOF
企鹅群将你的命中率降至零。 你被企鹅们杀死。

EOF
            gameover
            exit 1
        else
            cat << EOF
但一群企鹅不会容忍压迫，你很快发现自己被封在一块冰里。 你呆在那里，完美地保存了128年。当你被解冻后，你可以继续你的冒险。

EOF
        fi
	else
        let HP=HP--
        export HP
	    echo "你要把事情看清楚，不要对企鹅大发雷霆。"
	fi
}

cat << EOF
其中一只鸟终于注意到你的存在。 它把头转向一边，似乎在招手让你走近。

EOF
printf "你要靠近吗？ y/n  "
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
    cat << EOF
你向前走了一步，那只鸟冲向你，张大了嘴。 

EOF
    printf "你现在手里恰好有条鱼吗？ y/n  "
    read RESP

    if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
        if grep  --quiet --only-matching fish <<< $I; then
            cat << EOF

你把鱼扔给企鹅，企鹅在半空中接住了鱼。并把它吞了下去。

别忘了把鱼从你的库存中取出来。 试试下面的命令。

export I=\$(sed "s/fish//; s/,,/,/" <<< \$I)

EOF
        else
            echo "你没有鱼！"
            echo
            penguin_bite
        fi
   else
        penguin_bite
   fi
else
    cat << EOF
你小心翼翼地从企鹅身边退开。 它对你失去了兴趣，蹒跚而去。

EOF

fi
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
##
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Well that didn't work!
