#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 
cat << EOF
符文是古代神秘主义者的语言，曾经统治过这片土地。
西面的墙上刻有符文，这是曾经统治这片土地的古代神秘主义者的语言。

EOF
printf "Do you want to read them? y/n  "
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
    cat << EOF
你回忆起绿色的凯特琳的课程，她教你
这些古老的字母。 

这些符文是关于如何召唤一个传送门的指示
将允许你走过一扇包含在墙壁中的无形的门
在墙上。

在Bash中，符号链接（symbolic link）是通往另一个文件或目录的*快捷方式。 创建一个从这个房间到相邻房间的链接。

ln -fs ../../../chapel/courtyard/aviary/hall portal

EOF
else
    cat << EOF
你决定也许最好让神奇的铭文保持原样。

EOF

fi



























































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./spell

