#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 

gameover () {
    cat << EOF > corpse
你看到一个被杀的冒险者的尸体在地牢的地板上。你在尸体上发现了以下物品。 

$I

EOF
    curr=`basename $PWD`
    while [ "$curr" != "entrance" ]; do
        pushd .. &> /dev/null
        dirs -c
        curr=`basename $PWD`
    done
    unset I
    unset HP
    $SHELL
}

# this runs after the statue has been "destroyed"
# and this file has been renamed to 'pieces'
if [ "$0" = "./pieces" ]; then
    cat << EOF
你在一个破碎的雕像的碎片中进行筛选。

你在雕像的残骸中没有发现任何有趣的东西。

EOF
    exit 1
fi

# start the statue encounter
cat << EOF
一个粗犷的雕像矗立在房间的角落。

EOF
printf "接近它吗？ y/n  "

read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
    cat << EOF
雕像涌现，隆隆作响。

谁胆敢闯入灵魂之室？

它向你挥舞着拳头，对你造成了5点伤害。

EOF

    # this does not change the user's HP,
    # it only calculates it after damage
    let "HP=HP-5"
    if [ "$HP" -le 0 ]; then
        cat << EOF
你已经被雕像杀死了。

游戏结束!

EOF
        gameover
        exit 1
    fi

    perl -pe 's/coins/diamonds/' -i ./treasure
    printf "你有剑吗？ y/n  "
    read RESP
    if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
       if grep  --quiet --only-matching 'sword' <<< $I; then
           cat <<EOF
你击中了雕像，它被打成了碎片!

然而，你已经受到了伤害。
从你的HP变量中减去5。

让 "HP=HP-5"

EOF
           mv statue pieces
       else
           cat << EOF
不，你没有！ 快跑！
你已经受到了动画雕像的伤害。
从你的HP变量中减去5。

让 "HP=HP-5"

EOF
           rm treasure
           rm spell
      fi
    else
        cat <<EOF
快跑！
你已经受到了动画雕像的伤害。
从你的HP变量中减去5。

让 "HP=HP-5"
EOF
   fi
else
    cat << EOF
你小心翼翼地避开雕像，回想着在闹鬼的地下墓穴深处，有活的石头在等待的故事。

EOF

fi













































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./statue

