#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
cat << EOF
角落里有一个腐朽的旧祭坛，是某个被遗忘的神。

地上有一个小饰物。 它看起来具有宗教性质。

EOF
printf "你想把饰品放回祭坛上吗？ y/n  "
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
    cat << EOF
你把这个饰品放在祭坛上。 你感觉到一股温柔的微风吹过房间。

EOF
    touch .bless
else
    printf "你想把这个饰品据为己有吗？ y/n  "
    read RESP
    if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
        echo "记得把饰品加到你的库存中去!"
        touch .curse
    else
        cat << EOF
你把小饰品留在原地。 你感到了一种巨大的悲伤：不得不继续前进。

EOF

        touch .curse
   fi
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./altar
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 


